name: render_env

# Combine: conda env export --from-history
# And packages installed with pip.

channels:
  - conda-forge
  - defaults
dependencies:
  - fastapi
  - numpy
  - pandas
  - pytest
  - python=3.6
  - scikit-learn
  - uvicorn
  - pip
  - pip:
      - cloudpickle
      - httpcore
      - httpx
      - requests
      - contextlib2