name: fastapi_endpoint

# Combine: conda env export --from-history
# And packages installed with pip.

channels:
  - conda-forge
  - defaults
dependencies:
  - fastapi
  - jupyter
  - jupyterlab
  - numpy
  - pandas
  - pytest
  - python=3.8
  - scikit-learn
  - uvicorn