name: Fastapi Endpoint Integration

on:
  workflow_dispatch:
  push:
    branches: [main]

    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "W504"
          max-line-length: "110"
          path: "."

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest-cov
          pytest tests/test_api.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
          pytest tests/test_train_data.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  
  deploy:
      needs: [lint, test]
      runs-on: ubuntu-latest
      permissions: # Required if github_deployment is set to true.
        deployments: write
      steps:
          - uses: actions/checkout@v3
          - uses: JorgeLNJunior/render-deploy@v1.4.2
            with:
              service_id: ${{ secrets.RENDER_SERVICE_ID }} # required
              api_key: ${{ secrets.RENDER_API_KEY }} # required
              github_deployment: true # Create a GitHub deployment. Optional
              github_token: ${{ secrets.GITHUB_TOKEN }} # Remove if github_deployment is false. Optional